name: Build for Linux

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.2

      - name: Get dependencies
        run: sudo apt update && sudo apt install xorg-dev

      - name: Package
        run: CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o Fetch-Github-Hosts

      - name: Compress
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          files: |
            LICENSE
            README.md
            Fetch-Github-Hosts
          outPath: fetch-github-hosts_${{ env.RELEASE_VERSION }}_linux_amd64.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          append_body: true
          files: fetch-github-hosts_${{ env.RELEASE_VERSION }}_linux_amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}