name: Build for MacOS

#on:
#  push:
#    tags:
#      - v*

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.2

      - name: Go tidy
        run: go mod tidy

      - name: Install fyne
        run: go get fyne.io/fyne/v2/cmd/fyne

      - name: Package for MacOS
        run: fyne package --release -os darwin

      - name: Compress
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          files: |
            LICENSE
            README.md
            Fetch-Github-Hosts.app
          outPath: fetch-github-hosts_${{ env.RELEASE_VERSION }}_macOS_amd64.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: fetch-github-hosts_${{ env.RELEASE_VERSION }}_macOS_amd64.tar.gz
          path: fetch-github-hosts_${{ env.RELEASE_VERSION }}_macOS_amd64.tar.gz
          retention-days: 1

#      - name: Release
#        uses: softprops/action-gh-release@v1
#        if: startsWith(github.ref, 'refs/tags/')
#        with:
#          draft: true
#          append_body: true
#          files: fetch-github-hosts_${{ env.RELEASE_VERSION }}_macOS_amd64.tar.gz
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}